version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
      
    steps:
      - checkout

      - run:
          name: Install build-base
          command: apk add --no-progress -q --no-cache build-base

      - run:
          name: Install docker-compose
          command: |
            set -x
            apk add --no-progress -q --no-cache python py-pip
            pip install docker-compose

      - setup_remote_docker

      - run:
          name: Build container
          command: docker-compose -f docker-compose.prod.yml build

      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.prod.yml up -d postgres
            docker-compose -f docker-compose.prod.yml run --rm web initdb
            docker-compose -f docker-compose.prod.yml run -e FLASK_DEBUG=1 --rm web test

      - deploy:
          name: Deploy if branch is master or develop
          command: |
            echo "${DEPLOY_HOST_KEY}" >> ~/.ssh/known_hosts
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag colournaming jstutters/colournaming:latest
              docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
              docker push jstutters/colournaming:latest
              ssh $DEPLOY_USERNAME deploy.sh
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              docker tag colournaming jstutters/colournaming:develop
              docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
              docker push jstutters/colournaming:develop
              ssh $DEPLOY_USERNAME deploy.sh
            else
              echo "Skipping deployment"
            fi
            
